from pygame import Color

GRID_SIZE = [1052, 200]

MENU_HEIGHT = 270

WINDOW_SIZE = [GRID_SIZE[0], GRID_SIZE[1] + MENU_HEIGHT]
BUTTON_WIDTH = 225
BUTTON_HEIGHT = 50
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)
MINI_BUTTON_SIZE = (100, 50)
WEIGHT_TEXTBOX_SIZE = (50, 50)
WARNING_WINDOW_SIZE = (300, 200)
BUTTON_MARGIN = 15

WIDTH = 20
HEIGHT = 20
MARGIN = 1

ROWS = (GRID_SIZE[1] - MARGIN) // (HEIGHT+MARGIN)
COLS = (GRID_SIZE[0] - MARGIN) // (WIDTH+MARGIN)

NOT_VISITED = 0
FOUND = 1
SHORTEST_PATH_NODE = 2
TO_WEIGHT = 3
WEIGHTED = 4
WALL = 5
CURR_VISITING = 6
VISITED = 7
DONE_VISITING = 8

NUM_COLOR_STEPS = 15
WIDTH_GROWTH_STEP_SIZE = (3*WIDTH)//(4*NUM_COLOR_STEPS)
HEIGHT_GROWTH_STEP_SIZE = (3*HEIGHT)//(4*NUM_COLOR_STEPS)

NUM_SP_COLOR_STEPS = 8
SP_WIDTH = WIDTH + 6*MARGIN
SP_HEIGHT = HEIGHT + 6*MARGIN
WIDTH_SP_GROWTH_STEP_SIZE = (SP_WIDTH - WIDTH//4)//NUM_SP_COLOR_STEPS
HEIGHT_SP_GROWTH_STEP_SIZE = (SP_HEIGHT - HEIGHT//4)//NUM_SP_COLOR_STEPS

WHITE = (255,255,255)

BACKGROUND_COLOR = Color("#003d47")
COLORS = {}
COLORS[NOT_VISITED] = WHITE
COLORS[VISITED] = Color("#ed7a0e")
COLORS[CURR_VISITING] = Color("#a8eb34")
COLORS[DONE_VISITING] = Color("#34ebbd")
COLORS[FOUND] = Color("#80aebe")
COLORS[SHORTEST_PATH_NODE] = Color("#05ffe6")
COLORS[TO_WEIGHT] = Color("#470f00")
COLORS[WEIGHTED] = Color("#61869b")
COLORS[WALL] = Color("#007e80")

# start and target node variables
START_COLOR = Color("#f3c9e4")
TARGET_COLOR = Color("#10a0cc")
PICKUP_COLOR = Color("#ff6600")

ARROW_COLOR = Color("#05ffe6")

TEXT_COLOR = (30, 100, 120)
